[package]
name = "all-is-cubes-ui"
version = "0.5.0"
authors = ["Kevin Reid <kpreid@switchb.org>"]
edition = "2021"
rust-version = "1.65"
description = "User interface subsystem for the all-is-cubes engine."
# TODO: add homepage = "..." when we have one
repository = "https://github.com/kpreid/all-is-cubes"
license = "MIT OR Apache-2.0"
categories = ["games", "gui"]

[dependencies]
all-is-cubes = { path = "../all-is-cubes", version = "0.5.0" }
exhaust = { workspace = true }
futures-core = { workspace = true }
futures-task = { workspace = true }
image = { workspace = true, features = ["png"] }
indoc = { workspace = true }
instant = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
futures-channel = { workspace = true }
futures-executor = { workspace = true }
pretty_assertions = { workspace = true }
