[package]
name = "all-is-cubes"
version = "0.1.0"
authors = ["Kevin Reid <kpreid@switchb.org>"]
edition = "2018"
publish = false # guard against accidents until things are stable

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
overflow-checks = true

[dependencies]
cgmath = "0.17.0"
lazy_static = "1.4.0"
num-traits = "0.2.12"
rayon = "1.3.1"
termion = "1.5.5"
