[package]
name = "all-is-cubes-desktop"
version = "0.1.2"
authors = ["Kevin Reid <kpreid@switchb.org>"]
edition = "2018"
# TODO: better description
description = "Recursive voxel game."
readme = "../README.md"
# TODO: add homepage = "..." when we have one
repository = "https://github.com/kpreid/all-is-cubes"
license = "MIT"
# TODO: revisit categories once it's more settled what's in this package
categories = ["games", "rendering"]

[[bin]]
name = "all-is-cubes"
path = "src/main.rs"
bench = false

[dependencies]
all-is-cubes = { path = "../all-is-cubes", version = "0.1.2" }
cgmath = "0.18.0"
clap = "2.33.3"
glfw = "0.41"
luminance = "0.43.1"
luminance-front = "0.3.1"
luminance-glfw = "0.14"
luminance-windowing = "0.9"
once_cell = "1.4.1"
termion = "1.5.5"
