[package]
name = "all-is-cubes-gpu"
version = "0.4.0"
authors = ["Kevin Reid <kpreid@switchb.org>"]
edition = "2021"
rust-version = "1.60"
description = "Optional GPU rendering implementation for the all-is-cubes crate."
# TODO: add homepage = "..." when we have one
repository = "https://github.com/kpreid/all-is-cubes"
license = "MIT"
# TODO: revisit categories once it's more settled how useful this is as an engine
categories = ["games", "graphics", "rendering::engine"]

[lib]
# Disable running as benchmark so that the default doesn't interfere with Criterion usage.
bench = false

[features]
wgpu = ["dep:wgpu"]

[dependencies]
all-is-cubes = { path = "../all-is-cubes", version = "0.4.0" }
bytemuck = { version = "1.7.2", default-features = false, features = ["derive"] }
futures-core = { version = "0.3.17", default-features = false, features = ["alloc"] }
instant = "0.1.9"
log = { version = "0.4.14", default-features = false }
luminance = "0.47.0"
once_cell = "1.4.1"
rand = { version = "0.8.2", default-features = false }
rand_xoshiro = "0.6.0"
resource = "0.5.0"
thiserror = "1.0.22"
wgpu = { version = "0.12.0", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wgpu = { version = "0.12.0", optional = true, features = ["webgl"] }
# If we don't set this feature, it will try to access files at run time and fail
# since web wasm has no std::fs.
resource = { version = "0.5.0", features = ["force-static"] }
