[package]
name = "all-is-cubes-server"
version = "0.1.0"
authors = ["Kevin Reid <kpreid@switchb.org>"]
edition = "2018"
publish = false # guard against accidents until things are stable

[[bin]]
name = "aic-console"

[dependencies]
all-is-cubes = { path = "../all-is-cubes" }
cgmath = "0.17.0"
itertools = "0.9.0"
lazy_static = "1.4.0"
num-traits = "0.2.12"
rayon = "1.3.1"
termion = "1.5.5"
luminance = "0.41.0"
luminance-derive = "0.6.1"
luminance-front = "0.2.3"
luminance-windowing = "0.9.1"
