[package]
name = "all-is-cubes-server"
version = "0.1.0"
authors = ["Kevin Reid <kpreid@switchb.org>"]
edition = "2018"
description = "Game server and text-mode utilities for the recursive voxel game All is Cubes."
readme = "../README.md"
# TODO: add homepage = "..." when we have one
repository = "https://github.com/kpreid/all-is-cubes"
license = "MIT"
# TODO: revisit categories once it's more settled what's in this package
categories = ["games", "rendering"]

[[bin]]
name = "aic-console"

[dependencies]
all-is-cubes = { path = "../all-is-cubes", version = "0.1.0" }
cgmath = "0.17.0"
itertools = "0.9.0"
lazy_static = "1.4.0"
num-traits = "0.2.12"
rayon = "1.3.1"
termion = "1.5.5"
typed-arena = "2.0.1"
