[package]
name = "all-is-cubes"
version = "0.1.2"
authors = ["Kevin Reid <kpreid@switchb.org>"]
edition = "2018"
description = "Recursive voxel game/engine. Can be used for lo-fi voxel raytracing."
readme = "../README.md"
# TODO: add homepage = "..." when we have one
repository = "https://github.com/kpreid/all-is-cubes"
license = "MIT"
# TODO: revisit categories once it's more settled how useful this is as an engine
categories = ["games", "graphics"]

[[bench]]
name = "lighting"
harness = false

[features]
default = ["lum"]
# Unfortunately, we need a different name to avoid the feature name conflicting with
# the package name.
lum = ["luminance", "luminance-derive", "luminance-front"]

[dependencies]
cgmath = "0.17.0"
embedded-graphics = "0.6.2"
indexmap = "1.6.0"
itertools = "0.9.0"
once_cell = "1.4.1"
luminance = { version = "0.41.0", optional = true }
luminance-derive = { version = "0.6.1", optional = true }
luminance-front = { version = "0.2.3", optional = true }
num-traits = "0.2.12"
ordered-float = "2.0.0"
owning_ref = "0.4.1"
rand = "0.7.3"
rand_xoshiro = "0.4.0"

[dev-dependencies]
criterion = "0.3"
