[package]
name = "all-is-cubes"
version = "0.1.1"
authors = ["Kevin Reid <kpreid@switchb.org>"]
edition = "2018"
description = "Recursive voxel game/engine. Can be used for lo-fi voxel raytracing."
readme = "../README.md"
# TODO: add homepage = "..." when we have one
repository = "https://github.com/kpreid/all-is-cubes"
license = "MIT"
# TODO: revisit categories once it's more settled how useful this is as an engine
categories = ["games", "graphics"]

[[bench]]
name = "lighting"
harness = false

[dependencies]
cgmath = "0.17.0"
embedded-graphics = "0.6.2"
itertools = "0.9.0"
lazy_static = "1.4.0"
num-traits = "0.2.12"
owning_ref = "0.4.1"
rand = "0.7.3"
rand_xoshiro = "0.4.0"

[dev-dependencies]
criterion = "0.3"
