[package]
name = "all-is-cubes"
version = "0.2.1"
authors = ["Kevin Reid <kpreid@switchb.org>"]
edition = "2018"
description = "Recursive voxel game engine. Can be used for voxel raytracing."
# TODO: add homepage = "..." when we have one
repository = "https://github.com/kpreid/all-is-cubes"
license = "MIT"
# TODO: revisit categories once it's more settled how useful this is as an engine
categories = ["games", "graphics"]

[lib]
# Disable running as benchmark so that the default doesn't interfere with Criterion usage.
bench = false

[[bench]]
name = "lighting_bench"
harness = false

[[bench]]
name = "raycast_bench"
harness = false

[[bench]]
name = "space_bench"
harness = false

[[bench]]
name = "triangulator_bench"
harness = false

[features]
default = ["lum"]
# Unfortunately, we need a different name to avoid the feature name conflicting with
# the package name.
lum = ["luminance"]

[dependencies]
arbitrary = { version = "1.0.1", optional = true, features = ["derive"] }
bitvec = { version = "0.22.3", default-features = false, features = ["alloc"] }
bytemuck = { version = "1.7.2", default-features = false }
cgmath = "0.18.0"
embedded-graphics = "0.7.0"
instant = "0.1.9"
itertools = { version = "0.10.0", default-features = false }
log = { version = "0.4.14", default-features = false }
luminance = { version = "0.44.0", optional = true }
noise = { version="0.7.0", default-features = false }
num-traits = "0.2.12"
once_cell = "1.4.1"
ordered-float = { version = "2.1.1", features = ["serde"] }
ouroboros = "0.10.0"
rand = { version = "0.8.2", default-features = false }
rayon = { version = "1.3.1", optional = true }
rand_xoshiro = "0.6.0"
serde = { version = "1.0.126", default-features = false, features = ["derive"] }
strum = { version = "0.21.0", features = ["derive"] }
thiserror = "1.0.22"

[dev-dependencies]
criterion = "0.3.3"
indoc = "1.0.3"
pretty_assertions = "0.7.2"